-- Poynt integration tables schema
-- Generated by ChatGPT

-- =========================================================
-- NOVE TABLICE + SOURCE GET URL-ovi
-- =========================================================

-- =========================
-- ORDERS
-- =========================
-- Source (GET): /businesses/{businessId}/orders
--               /businesses/{businessId}/orders/{orderId}
CREATE TABLE IF NOT EXISTS "order" (
  order_id        VARCHAR(255) PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  store_id        VARCHAR(255),
  currency        VARCHAR(3),
  status                      VARCHAR(32),
  fulfillment_status          VARCHAR(32),
  transaction_status_summary  VARCHAR(32),
  subtotal_minor        BIGINT,
  discount_total_minor  BIGINT,
  tax_total_minor       BIGINT,
  tip_total_minor       BIGINT,
  fee_total_minor       BIGINT,
  shipping_total_minor  BIGINT,
  net_total_minor       BIGINT,
  tax_exempted    BOOLEAN,
  valid           BOOLEAN,
  accepted        BOOLEAN,
  notes           TEXT,
  customer_user_id BIGINT,
  employee_user_id BIGINT,
  store_device_id  VARCHAR(255),
  source           VARCHAR(32),
  source_app       VARCHAR(128),
  customer_json      JSONB NOT NULL DEFAULT '{}',
  transactions_json  JSONB NOT NULL DEFAULT '[]',
  amounts_json       JSONB NOT NULL DEFAULT '{}',
  context_json       JSONB NOT NULL DEFAULT '{}',
  raw_payload        JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_order_business_updated ON "order"(business_id, updated_at_ext);
CREATE INDEX IF NOT EXISTS idx_order_store_status     ON "order"(store_id, status);

CREATE TABLE IF NOT EXISTS order_item (
  order_id         VARCHAR(255) NOT NULL,
  order_item_id    VARCHAR(255) NOT NULL,
  product_id       VARCHAR(255),
  name             VARCHAR(255),
  sku              VARCHAR(255),
  category_id      VARCHAR(255),
  quantity         NUMERIC(18,3),
  unit_price_minor BIGINT,
  discount_minor   BIGINT,
  tax_minor        BIGINT,
  fee_minor        BIGINT,
  unit_of_measure  VARCHAR(32),
  status           VARCHAR(32),
  taxes_json       JSONB NOT NULL DEFAULT '[]',
  raw_payload      JSONB NOT NULL DEFAULT '{}',
  created_at_ext   TIMESTAMPTZ,
  updated_at_ext   TIMESTAMPTZ,
  PRIMARY KEY (order_id, order_item_id)
);
CREATE INDEX IF NOT EXISTS idx_order_item_product ON order_item(product_id);

CREATE TABLE IF NOT EXISTS order_history (
  order_id   VARCHAR(255) NOT NULL,
  event      VARCHAR(64),
  ts_ext     TIMESTAMPTZ,
  payload    JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (order_id, event, ts_ext)
);

CREATE TABLE IF NOT EXISTS order_shipment (
  order_id         VARCHAR(255) NOT NULL,
  shipment_id      VARCHAR(255) NOT NULL,
  status           VARCHAR(32),
  amount_minor     BIGINT,
  carrier          VARCHAR(64),
  tracking_no      VARCHAR(128),
  fulfill_at_ext   TIMESTAMPTZ,
  shipped_at_ext   TIMESTAMPTZ,
  delivered_at_ext TIMESTAMPTZ,
  payload          JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (order_id, shipment_id)
);

-- =========================
-- TRANSACTIONS
-- =========================
CREATE TABLE IF NOT EXISTS transaction (
  transaction_id     VARCHAR(255) PRIMARY KEY,
  business_id        VARCHAR(255) NOT NULL,
  store_id           VARCHAR(255),
  order_id           VARCHAR(255),
  action             VARCHAR(32),
  status             VARCHAR(32),
  settlement_status  VARCHAR(32),
  settled            BOOLEAN,
  partially_approved BOOLEAN,
  txn_amount_minor       BIGINT,
  order_amount_minor     BIGINT,
  tip_amount_minor       BIGINT,
  cashback_amount_minor  BIGINT,
  currency               VARCHAR(3),
  card_brand         VARCHAR(32),
  last4              VARCHAR(4),
  entry_mode         VARCHAR(64),
  processor          VARCHAR(64),
  processor_status   VARCHAR(64),
  processor_code     VARCHAR(32),
  approval_code      VARCHAR(32),
  retrieval_ref      VARCHAR(64),
  batch_id           VARCHAR(64),
  customer_user_id   BIGINT,
  references_json    JSONB NOT NULL DEFAULT '[]',
  funding_source     JSONB NOT NULL DEFAULT '{}',
  context_json       JSONB NOT NULL DEFAULT '{}',
  raw_payload        JSONB NOT NULL DEFAULT '{}',
  created_at_ext     TIMESTAMPTZ,
  updated_at_ext     TIMESTAMPTZ,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_tx_business_updated ON transaction(business_id, updated_at_ext);
CREATE INDEX IF NOT EXISTS idx_tx_order            ON transaction(order_id);
CREATE INDEX IF NOT EXISTS idx_tx_action_status    ON transaction(action, status);

CREATE TABLE IF NOT EXISTS transaction_receipt (
  transaction_id VARCHAR(255) PRIMARY KEY,
  html           TEXT,
  payload        JSONB NOT NULL DEFAULT '{}',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================
-- CUSTOMERS
-- =========================
CREATE TABLE IF NOT EXISTS customer (
  customer_id     BIGINT PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  first_name      VARCHAR(255),
  last_name       VARCHAR(255),
  emails_json     JSONB NOT NULL DEFAULT '[]',
  phones_json     JSONB NOT NULL DEFAULT '[]',
  attributes      JSONB NOT NULL DEFAULT '{}',
  raw_payload     JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_customer_business_updated ON customer(business_id, updated_at_ext);

-- =========================
-- BUSINESS USERS
-- =========================
CREATE TABLE IF NOT EXISTS business_user (
  business_id    VARCHAR(255) NOT NULL,
  user_id        BIGINT       NOT NULL,
  first_name     VARCHAR(255),
  last_name      VARCHAR(255),
  role           VARCHAR(64),
  status         VARCHAR(32),
  credentials    JSONB NOT NULL DEFAULT '[]',
  employment     JSONB NOT NULL DEFAULT '{}',
  raw_payload    JSONB NOT NULL DEFAULT '{}',
  created_at_ext TIMESTAMPTZ,
  updated_at_ext TIMESTAMPTZ,
  PRIMARY KEY (business_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_business ON business_user(business_id, role);

-- =========================
-- PRODUCTS & VARIANTS
-- =========================
CREATE TABLE IF NOT EXISTS product (
  product_id      VARCHAR(255) PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  name            VARCHAR(255) NOT NULL,
  sku             VARCHAR(255),
  price_minor     BIGINT,
  currency        VARCHAR(3),
  category_id     VARCHAR(255),
  is_active       BOOLEAN,
  attributes      JSONB NOT NULL DEFAULT '{}',
  raw_payload     JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_product_business_updated ON product(business_id, updated_at_ext);

CREATE TABLE IF NOT EXISTS product_variant (
  product_id      VARCHAR(255) NOT NULL,
  variant_id      VARCHAR(255) NOT NULL,
  name            VARCHAR(255),
  sku             VARCHAR(255),
  price_minor     BIGINT,
  attributes      JSONB NOT NULL DEFAULT '{}',
  raw_payload     JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ,
  PRIMARY KEY (product_id, variant_id)
);

-- =========================
-- INVENTORY
-- =========================
CREATE TABLE IF NOT EXISTS inventory_summary (
  business_id     VARCHAR(255) NOT NULL,
  product_id      VARCHAR(255) NOT NULL,
  total_on_hand   NUMERIC(18,3),
  total_reserved  NUMERIC(18,3),
  updated_at_ext  TIMESTAMPTZ,
  payload         JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (business_id, product_id)
);

CREATE TABLE IF NOT EXISTS inventory (
  business_id     VARCHAR(255) NOT NULL,
  store_id        VARCHAR(255) NOT NULL,
  product_id      VARCHAR(255) NOT NULL,
  on_hand         NUMERIC(18,3),
  reserved        NUMERIC(18,3),
  updated_at_ext  TIMESTAMPTZ,
  payload         JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (business_id, store_id, product_id)
);

CREATE TABLE IF NOT EXISTS variant_inventory (
  business_id     VARCHAR(255) NOT NULL,
  store_id        VARCHAR(255) NOT NULL,
  product_id      VARCHAR(255) NOT NULL,
  variant_id      VARCHAR(255) NOT NULL,
  on_hand         NUMERIC(18,3),
  reserved        NUMERIC(18,3),
  updated_at_ext  TIMESTAMPTZ,
  payload         JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (business_id, store_id, product_id, variant_id)
);

-- =========================
-- CATALOGS & CATEGORIES
-- =========================
CREATE TABLE IF NOT EXISTS catalog (
  catalog_id      VARCHAR(255) PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  name            VARCHAR(255),
  device_id       VARCHAR(255),
  raw_payload     JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS catalog_product (
  catalog_id      VARCHAR(255) NOT NULL,
  product_id      VARCHAR(255) NOT NULL,
  position        INTEGER,
  payload         JSONB NOT NULL DEFAULT '{}',
  PRIMARY KEY (catalog_id, product_id)
);

CREATE TABLE IF NOT EXISTS category (
  category_id     VARCHAR(255) PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  name            VARCHAR(255),
  parent_id       VARCHAR(255),
  raw_payload     JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ
);

-- =========================
-- TAXES
-- =========================
CREATE TABLE IF NOT EXISTS tax (
  tax_id          VARCHAR(255) PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  name            VARCHAR(255),
  rate_bp         INTEGER,
  scope           VARCHAR(64),
  active          BOOLEAN,
  raw_payload     JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_tax_business ON tax(business_id, active);

-- =========================
-- PAYLINKS
-- =========================
CREATE TABLE IF NOT EXISTS paylink (
  paylink_id      VARCHAR(255) PRIMARY KEY,
  business_id     VARCHAR(255) NOT NULL,
  domain          VARCHAR(255),
  status          VARCHAR(32),
  amount_minor    BIGINT,
  currency        VARCHAR(3),
  metadata        JSONB NOT NULL DEFAULT '{}',
  created_at_ext  TIMESTAMPTZ,
  updated_at_ext  TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================
-- HOOKS & DELIVERIES
-- =========================
CREATE TABLE IF NOT EXISTS hook (
  hook_id        VARCHAR(255) PRIMARY KEY,
  business_id    VARCHAR(255) NOT NULL,
  url            TEXT,
  event_types    TEXT[],
  status         VARCHAR(32),
  raw_payload    JSONB NOT NULL DEFAULT '{}',
  created_at_ext TIMESTAMPTZ,
  updated_at_ext TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS hook_delivery (
  delivery_id      VARCHAR(255) PRIMARY KEY,
  hook_id          VARCHAR(255) NOT NULL,
  business_id      VARCHAR(255) NOT NULL,
  event_type       VARCHAR(128),
  delivered_at_ext TIMESTAMPTZ,
  status           VARCHAR(32),
  http_status      INTEGER,
  retry_count      INTEGER,
  raw_payload      JSONB NOT NULL DEFAULT '{}'
);

