CREATE TABLE IF NOT EXISTS transaction (
    id SERIAL PRIMARY KEY,
    transaction_id VARCHAR(255) UNIQUE NOT NULL,
    business_id VARCHAR(255) NOT NULL,
    amount BIGINT,
    tip_amount BIGINT,
    cashback_amount BIGINT,
    currency VARCHAR(3),
    card_brand VARCHAR(50),
    card_last4 VARCHAR(4),
    card_holder VARCHAR(255),
    card_exp_month SMALLINT,
    card_exp_year SMALLINT,
    processor VARCHAR(100),
    processor_status VARCHAR(50),
    processor_transaction_id VARCHAR(255),
    processor_auth_code VARCHAR(255),
    metadata JSON NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
