-- POYNT v4 SCHEMA (tenant-first clean DDL)
-- This version represents the minimal shared schema needed to bootstrap the
-- application. All business data now lives in per-tenant tables rendered from
-- `SQL/poynt-tenant-templates.sql` (and related template files) by the PHP
-- provisioner. No stored procedures are defined here; provisioning logic
-- executes in PHP.




-- GLOBAL REGISTRY
DROP TABLE business;
CREATE TABLE IF NOT EXISTS business (
    business_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    active BOOLEAN NOT NULL DEFAULT FALSE,
    initial_gathering BOOLEAN NOT NULL DEFAULT FALSE,
    trial_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    trial_expires_at TIMESTAMPTZ
);

-- TENANT SCHEMA TRACKING
CREATE TABLE IF NOT EXISTS tenant_schema_version (
    tenant_id VARCHAR(255) PRIMARY KEY,
    version INTEGER NOT NULL,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tenant_table_registry (
    business_id VARCHAR(255) NOT NULL,
    table_name VARCHAR(255) NOT NULL,
    template_version INTEGER NOT NULL,
    registered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (business_id, table_name)
);
CREATE INDEX IF NOT EXISTS idx_tenant_table_registry_business ON tenant_table_registry (business_id, template_version DESC);

CREATE TABLE IF NOT EXISTS app_token (
    business_id VARCHAR(255) PRIMARY KEY,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_app_token_expires_at ON app_token (expires_at);

CREATE TABLE IF NOT EXISTS merchant_token (
    business_id VARCHAR(255) PRIMARY KEY,
    access_token TEXT NOT NULL,
    refresh_token TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_merchant_token_expires_at ON merchant_token (expires_at);

CREATE TABLE IF NOT EXISTS subscription (
    subscription_id VARCHAR(255) PRIMARY KEY,
    business_id VARCHAR(255) NOT NULL,
    store_id VARCHAR(255) NOT NULL,
    plan_id VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    phase VARCHAR(50) NOT NULL,
    trial_start_at TIMESTAMPTZ,
    trial_end_at TIMESTAMPTZ,
    start_at TIMESTAMPTZ NOT NULL,
    current_period_end TIMESTAMPTZ,
    end_at TIMESTAMPTZ,
    cancel_at_period_end BOOLEAN NOT NULL DEFAULT FALSE,
    canceled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_subscription_current_period_end ON subscription (current_period_end);
CREATE INDEX IF NOT EXISTS idx_subscription_store_status ON subscription (store_id, status);

CREATE TABLE IF NOT EXISTS log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id UUID NOT NULL,
    type TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    level SMALLINT,
    channel VARCHAR(64),
    message TEXT,
    merchant VARCHAR(64),
    url TEXT,
    details JSONB NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_log_request_id ON log_template (request_id);
CREATE INDEX IF NOT EXISTS idx_log_type ON log_template (type);
CREATE INDEX IF NOT EXISTS idx_log_timestamp ON log_template (timestamp);
CREATE INDEX IF NOT EXISTS idx_log_channel ON log_template (channel);
CREATE INDEX IF NOT EXISTS idx_log_level ON log_template (level);
CREATE INDEX IF NOT EXISTS idx_log_details_jsonb ON log_template USING GIN (details);



select * from business;
select * from log order by id desc;
select * from "3fb53611-061a-4464-8ca7-0b91ca7c98cf_app_token";
select * from "3fb53611-061a-4464-8ca7-0b91ca7c98cf_merchant_token";

DROP TABLE IF EXISTS "3fb53611-061a-4464-8ca7-0b91ca7c98cf_log" CASCADE;
select * from "3fb53611-061a-4464-8ca7-0b91ca7c98cf_log";


SELECT schemaname, tablename
FROM pg_tables
WHERE tablename = '3fb53611-061a-4464-8ca7-0b91ca7c98cf_log';

select * from log order by id desc;
select * from app_token;
select * from merchant_token;
-- truncate app_token;
-- truncate merchant_token;

-- drop table app_token;
-- drop table merchant_token;

select * from "3fb53611-061a-4464-8ca7-0b91ca7c98cf_subscription";
select * from subscription;